services:
  postgres:
    image: postgres:15
    container_name: postgres
    env_file: .env
    restart: always
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
      - "-c"
      - "max_wal_senders=10"
      - "-c"
      - "max_replication_slots=10"
      - "-c"
      - "max_connections=200"
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - main
  data-generator:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.data-generator
    container_name: data-generator
    restart: "no"
    depends_on:
      postgres:
        condition: service_healthy
    env_file: .env
    networks:
      - main
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: zookeeper
    restart: unless-stopped
    env_file: .env
    ports:
      - "2181:2181"
    networks:
      - main
  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka
    env_file: .env
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    networks:
      - main
  debezium:
    image: debezium/connect:2.7.3.Final
    container_name: debezium
    depends_on:
      - kafka
      - postgres
    ports:
    - "8083:8083"
    environment:
      BOOTSTRAP_SERVERS: kafka:29092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: debezium_configs
      OFFSET_STORAGE_TOPIC: debezium_offsets
      STATUS_STORAGE_TOPIC: debezium_status
    networks:
      - main
    volumes:
      - ./debezium/connectors:/kafka/connect/etc/connector-templates

  flink-jobmanager:
      image: flink:1.17.2-scala_2.12-java11
      container_name: flink-jobmanager
      command: jobmanager
      ports:
          - '8081:8081'
      environment:
          - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager
      volumes:
        - ./flink-pipeline/target:/opt/flink/usrlib
      networks:
          - main
  flink-taskmanager:
      image: flink:1.17.2-scala_2.12-java11
      container_name: flink-taskmanager
      command: taskmanager
      depends_on:
          - flink-jobmanager
      environment:
          - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager
      volumes:
        - ./flink-pipeline/target:/opt/flink/usrlib
      networks:
          - main
  fastapi:
      build:
          context: .
          dockerfile: ./docker/Dockerfile.fastapi
      env_file: .env
      container_name: fastapi
      ports:
          - '8000:8000'
      volumes:
        - ./event-emitter:/app
      depends_on:
        postgres:
          condition: service_healthy
      networks:
          - main
  mkdocs:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.docs
    container_name: mkdocs
    ports:
      - "8001:8001"
    volumes:
      - ./docs:/app/docs
      - ./mkdocs.yml:/app/mkdocs.yml
    environment:
      - MKDOCS_WATCHDOG=1
  
  fulfillment-services:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.fulfillment-services
    container_name: fulfillment-services
    env_file: .env
    depends_on:
      - kafka
      - postgres
      - debezium
      - fastapi
    volumes:
      - ./fulfillment-services:/app
    command: ["python", "fulfillment-services.py"]
    restart: unless-stopped
    networks:
      - main
  loki:
    image: grafana/loki:3.0.0
    ports:
      - "3100:3100"
    volumes:
      - ./observability/loki-config.yml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - main

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel/config.yaml"]
    volumes:
      - ./observability/otel-collector-config.yml:/etc/otel/config.yaml
    ports:
      - "4317:4317"
      - "4318:4318"
    networks:
      - main

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    volumes:
    - ./observability/grafana/data:/var/lib/grafana
    - ./observability/grafana/dashboards:/var/lib/grafana/dashboards
    - ./observability/grafana/provisioning:/etc/grafana/provisioning 
    networks:
      - main
    
volumes:
  grafana-storage: 

networks:
  main:
    driver: bridge
  observability:
    driver: bridge