FROM python:3.10-slim
WORKDIR /app
RUN pip install --no-cache-dir fastapi uvicorn psycopg2-binary python-dotenv opentelemetry-sdk opentelemetry-exporter-otlp opentelemetry-api opentelemetry-instrumentation-fastapi
EXPOSE 8000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000","--reload"]