FROM python:3.10-slim
WORKDIR /app

RUN pip install --no-cache-dir watchdog confluent-kafka psycopg2-binary requests python-dotenv

CMD ["watchmedo", "auto-restart", "--patterns=*.py", "--recursive", "--", "python", "fulfillment-services.py"]
